[package]
name = "sc2pathlib"
version = "0.1.0"
edition = "2018"

[lib]
name = "sc2pathlib"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]

[dependencies]
pathfinding = "1.1.12"